---
- name: Converge
  hosts: all
  gather_facts: False
  tasks:
    - name: Install net-tools for tests
      raw: test -e /usr/bin/netstat || (yum install -y net-tools)
      become: True
      changed_when: False

- name: Converge
  hosts: all
  become: True
  roles:
    - role: ansible-nginx-common
